web:
  dist: ./apps/web/dist
web-infra:
  stage: development
  serviceName: "erikoIkedaWeb"
  awsAccount: "350794894992"
  awsRegion: 'ap-northeast-1'
  deploymentStackName: "erikoIkedaWeb-deployment-dev"
  applicationStackName: "erikoIkedaWeb-application-dev"
  deployRoleName: "erikoIkedaWeb-deploy-role-dev"
  deployUserName: "personal"
  deployCiUserName: "ci"
  s3BucketName: "eriko-ikeda-web"
  sourceFilePath: "apps/web/dist"
  targetFilePath: "/"

